main:
	javac RC/*.java RoboComm/*.java RoboShare/*.java Tool/*.java
clean:
	rm -rf RC/*.class RoboComm/*.class RoboShare/*.class Tool/*.class
jar:	
	jar cmf manifest.mf rc.jar RC/*.class RoboComm/*.class RoboShare/*.class Tool/*.class
