#!/bin/sh
#
# Copyright 2004 The University of New South Wales (UNSW) and National  
# ICT Australia (NICTA).
#
# This file is part of the 2003 team rUNSWift RoboCup entry.  You may  
# redistribute it and/or modify it under the terms of the GNU General  
# Public License as published by the Free Software Foundation; either  
# version 2 of the License, or (at your option) any later version as  
# modified below.  As the original licensors, we add the following  
# conditions to that license:
#
# In paragraph 2.b), the phrase "distribute or publish" should be  
# interpreted to include entry into a competition, and hence the source  
# of any derived work entered into a competition must be made available  
# to all parties involved in that competition under the terms of this  
# license.
#
# In addition, if the authors of a derived work publish any conference  
# proceedings, journal articles or other academic papers describing that  
# derived work, then appropriate academic citations to the original work  
# must be included in that publication.
#
# This rUNSWift source is distributed in the hope that it will be useful,  
# but WITHOUT ANY WARRANTY; without even the implied warranty of  
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along  
# with this source code; if not, write to the Free Software Foundation,  
# Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#

# check that current dir is robot/
if [ ! -f install.py ]
then
    echo "install.py not found. Are you in the robot/ directory?"
    exit
fi

#call makefile.config like it was a shell script
. makefile.config

mountms
if cmp -s $MEMSTICK/open-r/VERSION.txt ./VERSION.txt; then
echo Correct OPEN_R_SDK found. 
cd PyCode && make clean && make && make check
if [ $? -ne 0 ] ; then
    cd ..
    exit
fi
cd ..
make prep
make -s install
umountms
else
echo WARNING: INCORRECT VERSION IN /usr/local/OPEN_R_SDK/. NEEDED:
echo
cat ./VERSION.txt
echo
echo FOUND
echo
cat $MEMSTICK/open-r/VERSION.txt
echo
echo INSTALLATION ABORTED
umountms
fi
